import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex justify-center  `}
      >
      <Script
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=zf2my9vk54`}
          strategy="beforeInteractive"
      />
      <div className={'max-w-[500px] w-full   flex flex-col  '}>


        {children}
          <NavBar/>
      </div>
      </body>
    </html>
  );
}
